### ISSUE TITLE
Adding SSTD'S does not show up in game

### ISSUE THREAD

**Issue by Seeker-Of-Knowledge** [start-5/TiTS.JS-Save-Editor#40]
When I use the status menu and add a sstd it adds it as a status but when I load the save in game and try to progress the sstd never shows up as an infection.  I also have a suggestion for the Furpies infection, maybe you could choose what type you get?

**Comment by start-5** [comment]
Alright, I had some time to look into this. Yes, the status effect is present but the issue is the editor doesn't currently support editing status effect duration, which is what the game depends on when dealing with this. If you know how to, you can set the `minutesLeft` property equal to 17280 and it should work as intended. 

I'm planning on finishing up status effects either today or tomorrow

> I also have a suggestion for the Furpies infection, maybe you could choose what type you get?

No clue how that works but it's most likely also something to do with status effects not being 100% supported yet
